version: '3.8'

services:
  server:
    build: .
    container_name: shipment-calculator
    ports:
      - "8086:80"
    environment:
      - PORT=80
      - PACK_SIZES_LOCATION=./priv/sizes.json 
  